using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{


    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        // if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
        //     BackgroundColor = bgColor;

    }
}
